// Code generated by MockGen. DO NOT EDIT.
// Source: ./contracts.go
//
// Generated by this command:
//
//	mockgen -source=./contracts.go -destination=./mocks/contracts_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	domain "github.com/gameap/gameap/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockResponder is a mock of Responder interface.
type MockResponder struct {
	ctrl     *gomock.Controller
	recorder *MockResponderMockRecorder
	isgomock struct{}
}

// MockResponderMockRecorder is the mock recorder for MockResponder.
type MockResponderMockRecorder struct {
	mock *MockResponder
}

// NewMockResponder creates a new mock instance.
func NewMockResponder(ctrl *gomock.Controller) *MockResponder {
	mock := &MockResponder{ctrl: ctrl}
	mock.recorder = &MockResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponder) EXPECT() *MockResponderMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockResponder) Write(ctx context.Context, rw http.ResponseWriter, result any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write", ctx, rw, result)
}

// Write indicates an expected call of Write.
func (mr *MockResponderMockRecorder) Write(ctx, rw, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockResponder)(nil).Write), ctx, rw, result)
}

// WriteError mocks base method.
func (m *MockResponder) WriteError(ctx context.Context, rw http.ResponseWriter, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteError", ctx, rw, err)
}

// WriteError indicates an expected call of WriteError.
func (mr *MockResponderMockRecorder) WriteError(ctx, rw, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteError", reflect.TypeOf((*MockResponder)(nil).WriteError), ctx, rw, err)
}

// MockRBAC is a mock of RBAC interface.
type MockRBAC struct {
	ctrl     *gomock.Controller
	recorder *MockRBACMockRecorder
	isgomock struct{}
}

// MockRBACMockRecorder is the mock recorder for MockRBAC.
type MockRBACMockRecorder struct {
	mock *MockRBAC
}

// NewMockRBAC creates a new mock instance.
func NewMockRBAC(ctrl *gomock.Controller) *MockRBAC {
	mock := &MockRBAC{ctrl: ctrl}
	mock.recorder = &MockRBACMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBAC) EXPECT() *MockRBACMockRecorder {
	return m.recorder
}

// AllowUserAbilitiesForEntity mocks base method.
func (m *MockRBAC) AllowUserAbilitiesForEntity(ctx context.Context, userID, entityID uint, entityType domain.EntityType, abilityNames []domain.AbilityName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowUserAbilitiesForEntity", ctx, userID, entityID, entityType, abilityNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// AllowUserAbilitiesForEntity indicates an expected call of AllowUserAbilitiesForEntity.
func (mr *MockRBACMockRecorder) AllowUserAbilitiesForEntity(ctx, userID, entityID, entityType, abilityNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowUserAbilitiesForEntity", reflect.TypeOf((*MockRBAC)(nil).AllowUserAbilitiesForEntity), ctx, userID, entityID, entityType, abilityNames)
}

// Can mocks base method.
func (m *MockRBAC) Can(ctx context.Context, userID uint, abilities []domain.AbilityName) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Can", ctx, userID, abilities)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Can indicates an expected call of Can.
func (mr *MockRBACMockRecorder) Can(ctx, userID, abilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Can", reflect.TypeOf((*MockRBAC)(nil).Can), ctx, userID, abilities)
}

// CanForEntity mocks base method.
func (m *MockRBAC) CanForEntity(ctx context.Context, userID uint, entityType domain.EntityType, entityID uint, abilities []domain.AbilityName) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanForEntity", ctx, userID, entityType, entityID, abilities)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanForEntity indicates an expected call of CanForEntity.
func (mr *MockRBACMockRecorder) CanForEntity(ctx, userID, entityType, entityID, abilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanForEntity", reflect.TypeOf((*MockRBAC)(nil).CanForEntity), ctx, userID, entityType, entityID, abilities)
}

// CanOneOf mocks base method.
func (m *MockRBAC) CanOneOf(ctx context.Context, userID uint, abilities []domain.AbilityName) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanOneOf", ctx, userID, abilities)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanOneOf indicates an expected call of CanOneOf.
func (mr *MockRBACMockRecorder) CanOneOf(ctx, userID, abilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanOneOf", reflect.TypeOf((*MockRBAC)(nil).CanOneOf), ctx, userID, abilities)
}

// GetRoles mocks base method.
func (m *MockRBAC) GetRoles(ctx context.Context, userID uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockRBACMockRecorder) GetRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockRBAC)(nil).GetRoles), ctx, userID)
}

// RevokeOrForbidUserAbilitiesForEntity mocks base method.
func (m *MockRBAC) RevokeOrForbidUserAbilitiesForEntity(ctx context.Context, userID, entityID uint, entityType domain.EntityType, abilityNames []domain.AbilityName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOrForbidUserAbilitiesForEntity", ctx, userID, entityID, entityType, abilityNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeOrForbidUserAbilitiesForEntity indicates an expected call of RevokeOrForbidUserAbilitiesForEntity.
func (mr *MockRBACMockRecorder) RevokeOrForbidUserAbilitiesForEntity(ctx, userID, entityID, entityType, abilityNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOrForbidUserAbilitiesForEntity", reflect.TypeOf((*MockRBAC)(nil).RevokeOrForbidUserAbilitiesForEntity), ctx, userID, entityID, entityType, abilityNames)
}

// SetRolesToUser mocks base method.
func (m *MockRBAC) SetRolesToUser(ctx context.Context, userID uint, roleNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRolesToUser", ctx, userID, roleNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRolesToUser indicates an expected call of SetRolesToUser.
func (mr *MockRBACMockRecorder) SetRolesToUser(ctx, userID, roleNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRolesToUser", reflect.TypeOf((*MockRBAC)(nil).SetRolesToUser), ctx, userID, roleNames)
}

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTransactionManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTransactionManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTransactionManager)(nil).Do), ctx, fn)
}
